-- Issue #17: a curated singular label for every RA 11904 sub-domain.
-- The seed is insert-only (ADR 0049), so it cannot fill this column on a
-- database that already has the sub-domains; this backfill does. It fills only
-- rows where singular_name is still null, so it never overwrites a label an
-- administrator has set. A sub-domain an administrator added that is not in
-- this list falls back to its own name, which they can then correct in
-- /admin/taxonomy.
UPDATE "creative_subdomains"
SET "singular_name" = CASE "slug"
  WHEN 'music-composers' THEN 'Music Composer'
  WHEN 'podcasts' THEN 'Podcast'
  WHEN 'voiceover-artists' THEN 'Voiceover Artist'
  WHEN 'film-production-companies' THEN 'Film Production Company'
  WHEN 'broadcasting-stations' THEN 'Broadcasting Station'
  WHEN 'animation-studios' THEN 'Animation Studio'
  WHEN 'digital-streaming-platforms' THEN 'Digital Streaming Platform'
  WHEN 'filmmakers' THEN 'Filmmaker'
  WHEN 'radio-tv-producers' THEN 'Radio and TV Producer'
  WHEN 'radio-tv-hosts' THEN 'Radio and TV Host'
  WHEN 'news-anchors-reporters' THEN 'News Anchor or Reporter'
  WHEN 'animators' THEN 'Animator'
  WHEN 'vloggers' THEN 'Vlogger'
  WHEN 'game-developers' THEN 'Game Developer'
  WHEN 'mobile-app-developers' THEN 'Mobile App Developer'
  WHEN 'video-game-designers' THEN 'Video Game Designer'
  WHEN 'virtual-reality-creators' THEN 'Virtual Reality Creator'
  WHEN 'augmented-reality-specialists' THEN 'Augmented Reality Specialist'
  WHEN 'digital-content-producers' THEN 'Digital Content Producer'
  WHEN 'gaming-studios' THEN 'Gaming Studio'
  WHEN 'mobile-app-development-firms' THEN 'Mobile App Development Firm'
  WHEN 'digital-content-platforms' THEN 'Digital Content Platform'
  WHEN 'advertising-creatives' THEN 'Advertising Creative'
  WHEN 'marketing-professionals' THEN 'Marketing Professional'
  WHEN 'research-development-experts' THEN 'Research and Development Expert'
  WHEN 'event-planners-coordinators' THEN 'Event Planner or Coordinator'
  WHEN 'live-performance-artists' THEN 'Live Performance Artist'
  WHEN 'cultural-experience-providers' THEN 'Cultural Experience Provider'
  WHEN 'communication-specialists' THEN 'Communication Specialist'
  WHEN 'graphic-designers' THEN 'Graphic Designer'
  WHEN 'architects' THEN 'Architect'
  WHEN 'urban-landscape-artists' THEN 'Urban Landscape Artist'
  WHEN 'environmental-planners' THEN 'Environmental Planner'
  WHEN 'interior-spatial-planners' THEN 'Interior and Spatial Planner'
  WHEN 'product-designers' THEN 'Product Designer'
  WHEN 'fashion-designers' THEN 'Fashion Designer'
  WHEN 'accessory-makers' THEN 'Accessory Maker'
  WHEN 'textile-developers' THEN 'Textile Developer'
  WHEN 'furniture-makers' THEN 'Furniture Maker'
  WHEN 'jewelry-artisans' THEN 'Jewelry Artisan'
  WHEN 'toy-makers' THEN 'Toy Maker'
  WHEN 'authors' THEN 'Author'
  WHEN 'print-journalists' THEN 'Print Journalist'
  WHEN 'comic-artists-publishers' THEN 'Comic Artist or Publisher'
  WHEN 'novelists' THEN 'Novelist'
  WHEN 'cartoonists' THEN 'Cartoonist'
  WHEN 'editorial-writers-columnists' THEN 'Editorial Writer or Columnist'
  WHEN 'magazine-editors' THEN 'Magazine Editor'
  WHEN 'newspaper-editors-companies' THEN 'Newspaper Editor or Company'
  WHEN 'choir-directors-trainers' THEN 'Choir Director or Trainer'
  WHEN 'musicians' THEN 'Musician'
  WHEN 'actors' THEN 'Actor'
  WHEN 'dance-choreographers' THEN 'Dance Choreographer'
  WHEN 'dancers-dance-troupes' THEN 'Dancer or Dance Troupe'
  WHEN 'theater-directors' THEN 'Theater Director'
  WHEN 'circus-performers' THEN 'Circus Performer'
  WHEN 'spoken-word-poets' THEN 'Spoken Word Poet'
  WHEN 'orchestras' THEN 'Orchestra'
  WHEN 'theater-companies' THEN 'Theater Company'
  WHEN 'painters' THEN 'Painter'
  WHEN 'sculptors' THEN 'Sculptor'
  WHEN 'photographers' THEN 'Photographer'
  WHEN 'multimedia-artists' THEN 'Multimedia Artist'
  WHEN 'collage-artists' THEN 'Collage Artist'
  WHEN 'tattoo-artists' THEN 'Tattoo Artist'
  WHEN 'art-galleries-studios' THEN 'Art Gallery or Studio'
  WHEN 'photography-studios' THEN 'Photography Studio'
  WHEN 'traditional-craftsmen' THEN 'Traditional Craftsperson'
  WHEN 'cultural-event-organizers' THEN 'Cultural Event Organizer'
  WHEN 'folk-musicians' THEN 'Folk Musician'
  WHEN 'indigenous-craft-artisans' THEN 'Artisan of Indigenous Crafts'
  WHEN 'crafts-cooperatives' THEN 'Crafts Cooperative'
  WHEN 'cultural-festivals' THEN 'Cultural Festival'
  WHEN 'traditional-cuisine-restaurants' THEN 'Traditional Cuisine Restaurant'
  WHEN 'folk-music-ensembles' THEN 'Folk Music Ensemble'
  WHEN 'museum-curators' THEN 'Museum Curator'
  WHEN 'archeologists' THEN 'Archeologist'
  WHEN 'librarians' THEN 'Librarian'
  WHEN 'provincial-municipal-city-planners' THEN 'Provincial, Municipal or City Planner'
  WHEN 'monumental-sculptors' THEN 'Monumental Sculptor'
  WHEN 'event-curators' THEN 'Event Curator'
  ELSE "name"
END
WHERE "singular_name" IS NULL;
